# Generated by Django 5.0.4 on 2024-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.IntegerField(default=9837, max_length=13),
            preserve_default=False,
        ),
    ]
