# Generated by Django 5.0.4 on 2024-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_customuser_delete_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
