# Generated by Django 5.0.4 on 2024-04-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_remove_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('app_ser', models.CharField(max_length=100)),
                ('app_doc', models.CharField(max_length=100)),
                ('app_user_name', models.CharField(max_length=100)),
                ('app_email', models.CharField(max_length=100)),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
