# Generated by Django 5.0.4 on 2024-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='password',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_ser',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Check Up'), (2, 'Surgery'), (3, 'Test')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_user_name',
            field=models.CharField(max_length=255),
        ),
    ]
