# Generated by Django 5.0.4 on 2024-04-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_remove_appointment_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_ser',
            field=models.CharField(max_length=100),
        ),
    ]
